### ISSUE TITLE
Incompatibility between doclicense and silence (Regression)

### ISSUE THREAD

**Issue by thbde** [ypid/latex-packages#78] opened 2021-06-28 19:24 UTC
The following does not fully compile with pdftex, but hangs in a endless loop:
```latex
\RequirePackage{silence}
\documentclass[a4paper]{report}
\usepackage[type={CC},modifier={by},version={4.0}]{doclicense}

\begin{document}
Thanks for your great work with doclicense!
\end{document}
```
Output of `\listfiles`:

- `silence.sty    2012/07/02 v1.5b`
- `doclicense.sty    2016/04/24 v1.5.0`

Expected behavior: Well, the example above compiles and I get a pdf.

Observations:

1. It seems to be a regression:
   1.  `doclicense.sty    2016/04/24 v1.5.0` # **works** (used in my overleaf project)
   2.  `doclicense.sty    2021/03/13 v2.3.0` # **does not work, hangs** (recent local TexLive installation)
2. `silence` seems to be in general considered as outdated. However, it seems to be the only way to block warnings in third party code that I cannot influence (like in `ifplatform`). Therefore, getting rid of `silence` is not a suitable option.
3. Google finds: https://www.mrunix.de/forums/showthread.php?77506-Probleme-mit-dem-doclicense-und-silence-Paket with a discussion + fix that compiles. See below.
4. Apparently, it seems to be an issue in `silence` (one may find more evidences by searching for `silence` and `Terminator` or by searching for `silence` and `hyperref`. Now we could argue that `silence` should be fixed (and I would in general agree). However, `silence` seems to be not updated anymore (which is a very weak argument, but still) and `doclicense `worked with `silence `in older versions of `doclicense`. Avoiding regressions could maybe a strong argument for an adaption of `doclicense`.

With the change from: https://www.mrunix.de/forums/showthread.php?77506-Probleme-mit-dem-doclicense-und-silence-Paket, the example from above compiles successfully.
```latex
\RequirePackage{silence}
%the next 3 lines are new
\makeatletter
\def\sl@Terminator{\null}
\makeatother
\documentclass[a4paper]{report}
\usepackage[type={CC},modifier={by},version={4.0}]{doclicense}

\begin{document}
Thanks for your great work with doclicense!
\end{document}
```

**Comment by ypid** [comment] 2021-06-28 21:18
This seems to be caused by hyperxmp actually, maybe even the interaction between hyperref and hyperxmp. I am working on a warning similar to #69.

```latex
\RequirePackage{silence}
\documentclass[a4paper]{report}
\usepackage[hyperxmp=false,type={CC},modifier={by},version={4.0}]{doclicense}

\begin{document}
Thanks, you are welcome :)
\end{document}
```

**Comment by ypid** [comment] 2021-06-28 22:49
I propose #83. But in your case, that results in a new warning from doclicense. I have the feeling that you don’t like warnings. Ideally, this would be fixed in hyperxmp or silence. They are both under the LaTeX Project Public License which actually defines how a new maintainer can take over maintenance. Please consider that.

**Comment by thbde** [comment] 2021-06-29 00:29
Thank you very much for considering the issue. I really do not feel comfortable to put a burden here on `doclicense` as the issue seems to be caused by `silence`. The regression was the strong argument from my side as it could be frustrating for non-experts if they come back to a latex document and it hangs during compilation.

Regarding the change: I am not a Latex expert in detail. Maybe it could be possible to detect the issue on a "feature-level" instead of a package level? It may be unlikely to be soon, but if the silence package is fixed, then the check here might be wrong. I am honest, I will not remember this check in 10 years.

Other than that, it is a bit unfortunate that we do not get the metadata, but this is no showstopper.

> I have the feeling that you don’t like warnings.

Well, point for you :) Warnings serve a purpose and therefore I try to get rid of them (without silencing them...).
Here, I could live with the approach proposed by #83. If I load the silence package, then I could also block this specific warning.

**Comment by ypid** [comment] 2021-06-29 16:53
> "feature-level" instead of a package level

Good idea but for that, I would need to debug the two packages to find the bug to do this feature or rather bug-level detection. And then I should rather fix the bug. But that is a bit out of scope for me.

So I merge #83 then. This workaround is in the workaround section and I will probably test if the workaround is still needed every other TeXLive release or so.

**Closed** 2021-06-29 16:53 UTC

**Comment by thbde** [comment] 2021-06-30 00:15
Ok, I understand. Fine for me. And again thank you very much for taking care of this issue.
