### ISSUE TITLE
Full localization of the license text

### ISSUE THREAD

**Issue by NiranjanTambe** [ypid/latex-packages#59] opened 2020-06-29 06:24 UTC
Hello,

Edit(ypid): This issue basically discusses #58.

I have added a new language file for Marathi language, but it fails to change the license name. Try the following code. It uses package [`marathi`](https://ctan.org/pkg/marathi) (a new release) and [this](https://github.com/ypid/latex-packages/pull/58) newly created file. Kindly install both of them before running the code.

```
\documentclass{article}
\usepackage{marathi}
\usepackage[
    type={CC},
    modifier={by-sa},
    version={4.0},
]{doclicense}

\begin{document}
\doclicenseThis
\end{document}
```

This gives a nearly correct output. See the following screenshot -

![Screenshot-34](https://user-images.githubusercontent.com/54938729/85979789-c23f9500-b9fe-11ea-9f7d-84e8cee6ea99.png)

I wish to change the auto-generated-text `Creative Commons` to `क्रिएटिव्ह कॉमन्स`. This is nothing but the same name written in Devanagari script. I couldn't find it in the .ldf as well as in the sty. Can somebody explain me from where can I change this text?

PS - Also a bit difficult one. I want to change the text in the image. Is there any open access svg of this file, in which I can insert Devanagari text?

**Comment by NiranjanTambe** [comment] 2020-06-29 06:41
I tried adding this to the .ldf file, but the output still shows `Creative Commons` in English.
```
\ifthenelse{\equal{\doclicense@type}{CC}}{%
    \renewcommand*{\doclicenseLongType}{क्रिएटिव्ह कॉमन्सच्या }}{}
```

**Comment by NiranjanTambe** [comment] 2020-06-29 07:31
Thanks, I understood the problem. ldf files are loaded before the line 264 of the sty file. Thus any name in the ldf file is renewed by that definition. Using `\AtBeginDocument` solved the problem.

```
\AtBeginDocument{\ifthenelse{\equal{\doclicense@type}{CC}}{%
    \renewcommand*{\doclicenseLongType}{क्रिएटिव्ह कॉमन्सच्या\xspace}}{}}
```

**Comment by NiranjanTambe** [comment] 2020-06-29 07:35
This change is now added in the [`doclicense-marathi.ldf`](https://github.com/NiranjanTambe/latex-packages/commit/ee04cce4a66779576b2db50a96dd7e8e540b7970).

I still wish to add Devanagari text in the creative commons images. Please guide me to its source svg files.

Thanks :)

**Comment by NiranjanTambe** [comment] 2020-06-29 11:29
[This](https://github.com/ypid/latex-packages/files/4845080/mr-images.zip) is a zip containing all the changed images.

Kindly suggest a way to incorporate these images when Marathi language is loaded. I added these file in the following path

```
/texmf-dist/tex/latex/doclicense/images/
```

Then added the following line in [`doclicense-marathi.ldf`](https://github.com/NiranjanTambe/latex-packages/commit/ee04cce4a66779576b2db50a96dd7e8e540b7970).

```
\AtBeginDocument{\renewcommand{\doclicenseImageFileName}{%
  doclicense-\doclicense@type-\doclicense@modifier\doclicense@imagemodifier-mr}}
```

This code loads the image-file correctly, but the hyperlink is not shown properly. Hyperlink comes as a small box next to the image file. It should be placed correctly. Any help?

**Comment by ypid** [comment] 2020-06-29 21:16
> Can somebody explain me from where can I change this text?

I made it translatable in #60.

> This is a zip containing all the changed images.

You asked above for SVG files that you could edit. I would prefer that as it is a vector file format from which I have scripts to generate both PDF (for pdflatex/lualatex) and EPS (latex). https://github.com/ypid/latex-packages/blob/master/doclicense/images/Makefile Could you redo your changes to those files with something like Inkscape? You need to download them from https://mirrors.creativecommons.org/presskit/buttons

I will look into the hyperlink issue later.

**Comment by NiranjanTambe** [comment] 2020-06-30 07:02
> I made it translatable in #60.

Thanks. I didn't know that command :)

I have tried to do it, but I have omitted sampling plus licenses as they are obsolete. I really don't know how to obtain a pdf out of eps files. Currently you can find all the eps and svg files in the following zip.

[eps_svg_files.zip](https://github.com/ypid/latex-packages/files/4849977/eps_svg_files.zip)

**Comment by ypid** [comment] 2020-06-30 19:40
I just need the SVG files. I can generate everything using Inkscape in batch mode (see the [Makefile](https://github.com/ypid/latex-packages/blob/master/doclicense/images/Makefile)).

**Comment by NiranjanTambe** [comment] 2020-07-01 02:03
Okay :)

I am waiting for your response. Also please remember the hyperlink issue is pending

**Comment by ypid** [comment] 2020-07-09 09:34
I re-thought this. There is a similar discussion going on in #57 about adding images. My standpoint is to talk to creativecommons.org first to see if they can make this official. Not sure why I have not suggested that here from the start. Can you ask them what they think about your modifications?

**Comment by NiranjanTambe** [comment] 2020-07-10 11:37
I contacted them already, but no response from that side :( It has been more than two weeks now. I think as the material is licensed with `CC-BY`, we can modify and share the material. That shall not be a problem for them.

**Comment by ypid** [comment] 2020-07-10 16:39
License should be no issue, I agree. But it is an issue for this package. I guess we can solve it by declaring those images as unofficial. Then it should be fine. What do you think? I guess a note in the supported languages section should be enough.

**Comment by NiranjanTambe** [comment] 2020-07-11 08:04
> I guess we can solve it by declaring those images as unofficial. Then it should be fine. What do you think? I guess a note in the supported languages section should be enough, plus, the images might get the flag "unofficial" in their filename in case someone finds them.

That's alright, but I just have one query. What is "official" in the image for Euro? I don't see any note on the official site of creative commons. IMO it's always public initiative to localize free works. Per say I have no problem with adding unofficial to file-names as anyways they are invisible to the users, but you should think again about adding an unofficial mark to these images and if you are firm on adding this tag, ideally you should also add it to the European version.

**Comment by ypid** [comment] 2020-07-14 11:41
I consider the files on https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/ as official ;-)

**Comment by NiranjanTambe** [comment] 2020-07-14 11:44
Fair enough :)

As right now it isn't part of the list, let's call it "unofficial" & distribute it, what say?

**Comment by NiranjanTambe** [comment] 2020-07-14 12:15
To make it a bit easier I have added a commit [here](https://github.com/ypid/latex-packages/pull/58/commits/60c32448859a116be45ff784067a1b5516adc50e). It includes all the latest changes. Latest addition is the rupee symbol for the NC logo.

**Comment by ypid** [comment] 2020-07-20 22:26
Thanks. I now dedicated the time to work on it. #58 is updated, feel free to do your final testing and tell me if I can merge it.

About the hyperlink issue, I can not reproduce this without the https://ctan.org/pkg/marathi package (which did not work for me, maybe some Unicode issue, I have not debugged). I don’t see where I could have a bug there. Can you try to reproduce this with as few packages as possible, especially with another language like English. I don’t know anything about Marathi but it also messed with my editor Vim, when I edited the translation files ;-)

**Comment by NiranjanTambe** [comment] 2020-07-21 06:24
Thanks for your work.

I have spotted a minor error. Text doesn't look proper in any of the generated files. For you to compare the visual form check this screenshot and [doclicense-CC-by-nc-nd-unofficial-mr-80x31.pdf](https://github.com/NiranjanTambe/latex-packages/blob/patch-1/doclicense/images/doclicense-CC-by-nc-nd-unofficial-mr-88x31.pdf)

![Screenshot-50](https://user-images.githubusercontent.com/54938729/88019848-4261a200-cb48-11ea-84e3-274e292568b9.png)

This is how the .svg file looks like on my inkscape. Probably because you don't have the font [Baloo2](https://ektype.in/scripts/devanagari/baloo2.html) it doesn't give similar output on your system. If you don't mind, may I request you to install it? I hope inkscape auto-detects the installed fonts and gives correct results.

Another option is just to tell me how to activate your `Makefile` to generate all the eps and pdf files. I'll generate them on my system check the visuals and push them to the directory. I can do the stuff from my terminal if you tell me the correct steps.

**Comment by NiranjanTambe** [comment] 2020-07-21 06:41
I also [added the svg files](https://github.com/ypid/latex-packages/pull/58/commits/9db17ebd8c2f3f83feedf9d8c94b82e8391c1aba) for 80x15 size. I hope the names are correct.

I have used the same font for the new files too. So if you decide to follow the first way (installing the font on your system and regenerating the files), you don't need to do anything special for these new files.

**Comment by ypid** [comment] 2020-07-21 14:33
> Another option is just to tell me how to activate your Makefile to generate all the eps and pdf files.

Lets try that. It is standard [GNU Make](https://www.gnu.org/software/make/manual/), which has extensive documentation. But in short. Delete the unofficial PDF and EPS files and run `make` (with default target). You will need to have GNU Make installed obviously.

**Comment by NiranjanTambe** [comment] 2020-07-21 16:11
I am getting error 1.

```
make
inkscape "doclicense-CC-by-nc-unofficial-mr-88x31.svg" --export-type=pdf --export-filename "doclicense-CC-by-nc-unofficial-mr-88x31.pdf"

** (inkscape:5648): WARNING **: 21:39:21.390: Invalid option --export-type=pdf
make: *** [Makefile:68: doclicense-CC-by-nc-unofficial-mr-88x31.pdf] Error 1
```

**Comment by NiranjanTambe** [comment] 2020-07-21 16:37
I tried to find the cause. It's not your fault. My inkscape version is older. I need to do distribution upgrade to compile the changes (which is tough).

Can we go with the first way?

**Comment by ypid** [comment] 2020-07-21 21:49
Just revert this commit https://github.com/ypid/latex-packages/commit/b21eea9345fbac4e912c2c9b4f2c81999dbaff55. I just updated to tackle a different issue. The version did not affect it as far as I can remember so you can safely use an older version I would say (maybe not too old).

Do you use Debian by any chance? Because there you have backports ;-)

**Comment by ypid** [comment] 2020-07-23 16:51
> Just revert this commit b21eea9.

I guess I put that wrong. With revert I meant use but do not commit ;-) But that is my mistake. Fixed.

Now I am only waiting on conformation about hyperref.

**Comment by NiranjanTambe** [comment] 2020-07-23 16:59
I actually did not revert the commit. I just changed the code manually, because reverting the commit also caused the loss of all the svg files which I did not want, but actually I changed it before committing. If I am not wrong your recent commit actually changes the newer code to the older one.

Hyperref issue doesn't come now. I don't know how, but it is fixed :)

**Comment by ypid** [comment] 2020-07-24 18:11
You are right, thanks for the hint.

Sounds good then. I merged #58 now so I will close this issue was well. I will release this in the next days because I also fixed a bug in the process.

**Closed by ypid** 2020-07-24 18:11 UTC

**Comment by NiranjanTambe** [comment] 2020-07-26 11:31
@ypid Thanks for taking this step. Can you please inform here when you release the package?

**Comment by ypid** [comment] 2020-07-28 18:34
> Can you please inform here when you release the package?

Sure, I published it Sunday. Yesterday evening when I checked, the announcement was not yet up. Now it is up:
https://ctan.org/ctan-ann/id/mailman.397.1595879477.2548.ctan-ann@ctan.org

Thanks again for your contribution :)

**Comment by NiranjanTambe** [comment] 2020-07-29 05:01
That's a really great news :+1:

Thank you so much for this initiative towards a healthy multilingual society.
